pins:
  - pin: 1
    function: Ground

  - pin: 2
    id: EFI_ADC_4
    class: analog_inputs
    function: Battery Sense
    type: av
    ts_name: Battery Sense

  - pin: 3/13
    id: PROTECTED_PIN_7
    class: outputs
    function: High Side Output
    type: hs
    ts_name: Out 8

  - pin: 4/14
    id: PROTECTED_PIN_6
    class: outputs
    function: High Side Output
    type: hs
    ts_name: Out 7

  - pin: 5/15
    id: PROTECTED_PIN_5
    class: outputs
    function: High Side Output
    type: hs
    ts_name: Out 6

  - pin: 6/16
    id: PROTECTED_PIN_4
    class: outputs
    function: High Side Output
    type: hs
    ts_name: Out 5

  - pin: 7/17
    id: PROTECTED_PIN_3
    class: outputs
    function: High Side Output
    type: hs
    ts_name: Out 4

  - pin: 8/18
    id: PROTECTED_PIN_2
    class: outputs
    function: High Side Output
    type: hs
    ts_name: Out 3

  - pin: 9/19
    id: PROTECTED_PIN_1
    class: outputs
    function: High Side Output
    type: hs
    ts_name: Out 2

  - pin: 10
    id: PROTECTED_PIN_0
    class: outputs
    function: High Side Output
    type: hs
    ts_name: Out 1

  - pin: 11
    function: CAN Low

  - pin: 12
    function: CAN High

  - pin: 3/13
    id: EFI_ADC_9
    class: analog_inputs
    function: Current Sense
    type: av
    ts_name: Sense 8

  - pin: 4/14
    id: EFI_ADC_8
    class: analog_inputs
    function: Current Sense
    type: av
    ts_name: Sense 7

  - pin: 5/15
    id: EFI_ADC_15
    class: analog_inputs
    function: Current Sense
    type: av
    ts_name: Sense 6

  - pin: 6/16
    id: EFI_ADC_14
    class: analog_inputs
    function: Current Sense
    type: av
    ts_name: Sense 5

  - pin: 7/17
    id: EFI_ADC_13
    class: analog_inputs
    function: Current Sense
    type: av
    ts_name: Sense 4

  - pin: 8/18
    id: EFI_ADC_12
    class: analog_inputs
    function: Current Sense
    type: av
    ts_name: Sense 3

  - pin: 9/19
    id: EFI_ADC_11
    class: analog_inputs
    function: Current Sense
    type: av
    ts_name: Sense 2

  - pin: 20
    id: EFI_ADC_10
    class: analog_inputs
    function: Current Sense
    type: av
    ts_name: Sense 1

info:
  cid: tdg-pdm8
  title: tdg-pdm8
  directory: tdg-pdm8
  name: tdg-pdm8
  image:
    file: tdg-pdm8.jpg
  pins:
    - pin: 1
      x: 187
      y: 93

    - pin: 2
      x: 232
      y: 93

    - pin: 9
      x: 532
      y: 93

    - pin: 10
      x: 576
      y: 93

    - pin: 11
      x: 187
      y: 168

    - pin: 12
      x: 232
      y: 168

    - pin: 19
      x: 532
      y: 168

    - pin: 20
      x: 576
      y: 168
